### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by mflisikowski** [taylon/atom-lorempixel#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.0
**System**: Unknown Windows Version
**Thrown From**: [atom-lorempixel](https://github.com/taylon/atom-lorempixel) package, v0.1.0
### Stack Trace

Uncaught TypeError: Cannot read property 'querySelector' of null

```
At /D:/Users/mflisikowski/.atom/packages/jshint/index.js:185

TypeError: Cannot read property 'querySelector' of null
    at addReasons (D:/Users/mflisikowski/.atom/packages/jshint/index.js:168:41)
    at displayError (D:/Users/mflisikowski/.atom/packages/jshint/index.js:194:2)
    at D:/Users/mflisikowski/.atom/packages/jshint/index.js:201:24
    at arrayEach (D:\Users\mflisikowski\AppData\Local\atom\app-1.3.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:1289:13)
    at Function.<anonymous> (D:\Users\mflisikowski\AppData\Local\atom\app-1.3.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:3345:13)
    at displayErrors (D:/Users/mflisikowski/.atom/packages/jshint/index.js:201:4)
    at lint (D:/Users/mflisikowski/.atom/packages/jshint/index.js:275:2)
    at complete (D:\Users\mflisikowski\AppData\Local\atom\app-1.3.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7697:25)
    at delayed (D:\Users\mflisikowski\AppData\Local\atom\app-1.3.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7707:11)
```
### Commands

```
     -3:04.9.0 core:backspace (input.hidden-input)
     -3:04.6.0 core:save (input.hidden-input)
  2x -2:39.3.0 core:backspace (input.hidden-input)
     -2:38.5.0 core:save (input.hidden-input)
     -1:18.6.0 core:paste (input.hidden-input)
     -1:17.4.0 core:save (input.hidden-input)
  3x -1:00.3.0 core:backspace (input.hidden-input)
     -0:54.5.0 core:save (input.hidden-input)
     -0:38.3.0 core:backspace (input.hidden-input)
     -0:37.1.0 core:save (input.hidden-input)
  3x -0:11.3.0 core:backspace (input.hidden-input)
  2x -0:09.7.0 core:move-down (input.hidden-input)
     -0:08.7.0 core:move-up (input.hidden-input)
  2x -0:08.4.0 core:select-up (input.hidden-input)
     -0:07.8.0 core:backspace (input.hidden-input)
     -0:06.4.0 core:save (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autoprefixer",
      "atom-sync",
      "git-diff",
      "dev-live-reload",
      "keybinding-resolver",
      "markdown-preview",
      "package-generator",
      "atom-beautify"
    ],
    "openEmptyEditorOnStart": false,
    "autoHideMenuBar": true,
    "packagesWithKeymapsDisabled": [
      "gulp-control"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-lorempixel, v0.1.0
autoclose-html, v0.19.0
bezier-curve-editor, v0.7.2
compare-files, v0.6.2
css-comb, v2.4.0
editor-stats, v0.17.0
editorconfig, v1.2.2
file-type-icons, v0.7.4
git-hide, v0.1.2
highlight-line, v0.11.0
jshint, v1.8.3
language-babel, v2.6.0
language-javascript-jsx, v0.3.7
language-log, v1.1.0
minimap, v4.17.0
pigments, v0.19.2
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by taylon** [comment]
Hey @MateuszFlisikowski I wasn't able to reproduce the issue, it seems to be a problem in another package, specially because this package only provides a snippet, it's really simple.

Are you still having problems?
